import { User, CreateUserDto, UpdateUserDto } from '../types/User';

export class UserService {
  private users: User[] = [
    { id: 1, name: 'John Doe', email: 'john@example.com', createdAt: new Date(), updatedAt: new Date() },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com', createdAt: new Date(), updatedAt: new Date() }
  ];

  public getAllUsers(): User[] {
    return this.users;
  }

  public getUserById(id: number): User | undefined {
    return this.users.find(user => user.id === id);
  }

  public createUser(userData: CreateUserDto): User {
    const newUser: User = {
      id: Date.now(), // In a real app, this would be generated by the database
      name: userData.name,
      email: userData.email,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    this.users.push(newUser);
    return newUser;
  }

  public updateUser(id: number, userData: UpdateUserDto): User | undefined {
    const userIndex = this.users.findIndex(user => user.id === id);
    
    if (userIndex === -1) {
      return undefined;
    }

    const existingUser = this.users[userIndex];
    if (!existingUser) {
      return undefined;
    }

    const updatedUser: User = {
      id: existingUser.id,
      name: userData.name ?? existingUser.name,
      email: userData.email ?? existingUser.email,
      createdAt: existingUser.createdAt ?? new Date(),
      updatedAt: new Date()
    };

    this.users[userIndex] = updatedUser;
    return updatedUser;
  }

  public deleteUser(id: number): boolean {
    const userIndex = this.users.findIndex(user => user.id === id);
    
    if (userIndex === -1) {
      return false;
    }

    this.users.splice(userIndex, 1);
    return true;
  }

  public getUserByEmail(email: string): User | undefined {
    return this.users.find(user => user.email.toLowerCase() === email.toLowerCase());
  }

  public searchUsers(query: string): User[] {
    const lowercaseQuery = query.toLowerCase();
    return this.users.filter(user => 
      user.name.toLowerCase().includes(lowercaseQuery) || 
      user.email.toLowerCase().includes(lowercaseQuery)
    );
  }
}
